parameters:
#    roxanne7_blog.example.class: Roxanne7\BlogBundle\Example

services:
#    roxanne7_blog.example:
#        class: %roxanne7_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
