roxanne7_vinnity:
    resource: "@Roxanne7VinnityBundle/Resources/config/routing.yml"
    prefix:   /

roxanne7_user:
    resource: "@Roxanne7UserBundle/Resources/config/routing.yml"
    prefix:   /user

login:
    pattern:   /login
    defaults:  { _controller: "Roxanne7UserBundle:Security:login" }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout