security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Roxanne7\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]       # Un admin hérite des droits d'auteur et de modérateur
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH] # On garde ce rôle superadmin, il nous resservira par la suite

    providers:
        main:
          entity: { class: Roxanne7\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
          pattern: ^/
          anonymous: true
          provider: main
          form_login:
            login_path: login
            check_path: login_check
          logout:
            path: logout
            target: /


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }