parameters:
#    roxanne7_vinnity.example.class: Roxanne7\VinnityBundle\Example

services:
#    roxanne7_vinnity.example:
#        class: %roxanne7_vinnity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
