Roxanne7_user_register:
  path: /register
  defaults:  {_controller: "Roxanne7UserBundle:UserManagement:register" }
  
Roxanne7_user_login:
  path: /login
  defaults:  {_controller: "Roxanne7UserBundle:UserManagement:login" }
  
Roxanne7_user_profile:
  path: /profile/{user}
  defaults:  {_controller: "Roxanne7UserBundle:UserManagement:profile", user: -1 }
    