Roxanne7_user_register:
  path: /register
  defaults:  {_controller: "Roxanne7UserBundle:UserManagement:register" }
  
Roxanne7_user_login:
  path: /login
  defaults:  {_controller: "Roxanne7UserBundle:UserManagement:login" }
  