parameters:
#    roxanne7_user.example.class: Roxanne7\UserBundle\Example

services:
#    roxanne7_user.example:
#        class: %roxanne7_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
