parameters:
#    roxanne7_user.example.class: Roxanne7\UserBundle\Example


services:
    roxanne7_user.registration.form.type:
        class: Roxanne7\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: roxanne7_user_registration }